### ISSUE TITLE
Issue using the code

### ISSUE THREAD

**Issue by bentoo** [NMZivkovic/BertTokenizers#1]
I am trying to use your code. 

var encoded = tokenizer.Encode(32, sentence);
            var result = model.Transform(encoded);
            var bertInput = new ModelInput()
            {
                InputIds = encoded.InputIds, // this does not compile because encoded is a list of tuples
                AttentionMask = encoded.AttentionMask,
                TokenTypeIds = encoded.TokenTypeIds,
            };

Can you provide a complete working example using ML.NET and your BertTokenizers?

**Comment by NMZivkovic** [comment]
Hi bentoo,

Thanks for the report.
The example is updated.
