### ISSUE TITLE
BertTokenizers in .NET 3.1 and/or .NET 6.0

### ISSUE THREAD

**Issue by ADD-eNavarro** [NMZivkovic/BertTokenizers#2]
Hello there.
I'm using Visual Studio Enterprise 2019 over Windows. I found and added your (wonderful) BERTTokenizers package without issue, but when I try to use it in Program.cs it's not recognized, meaning it won't show what trying to "using" it.
I have already reloaded the project, no changes. 
Please, what may I be doing wrong?

**Comment by NMZivkovic** [comment]
Latest version (1.10.0) contains .NET 6 support.
Thanks for contributing!
